var annotated_dup =
[
    [ "N2kStream", "class_n2k_stream.html", "class_n2k_stream" ],
    [ "tActisenseReader", "classt_actisense_reader.html", "classt_actisense_reader" ],
    [ "tN2kAISAtoNReportData", "structt_n2k_a_i_s_ato_n_report_data.html", "structt_n2k_a_i_s_ato_n_report_data" ],
    [ "tN2kCANMsg", "classt_n2k_c_a_n_msg.html", "classt_n2k_c_a_n_msg" ],
    [ "tN2kDD206", "uniont_n2k_d_d206.html", "uniont_n2k_d_d206" ],
    [ "tN2kDD223", "uniont_n2k_d_d223.html", "uniont_n2k_d_d223" ],
    [ "tN2kDD471", "uniont_n2k_d_d471.html", "uniont_n2k_d_d471" ],
    [ "tN2kDD475", "uniont_n2k_d_d475.html", "uniont_n2k_d_d475" ],
    [ "tN2kDD477", "uniont_n2k_d_d477.html", "uniont_n2k_d_d477" ],
    [ "tN2kDD478", "uniont_n2k_d_d478.html", "uniont_n2k_d_d478" ],
    [ "tN2kDD483", "uniont_n2k_d_d483.html", "uniont_n2k_d_d483" ],
    [ "tN2kDeviceList", "classt_n2k_device_list.html", "classt_n2k_device_list" ],
    [ "tN2kGroupFunctionHandler", "classt_n2k_group_function_handler.html", "classt_n2k_group_function_handler" ],
    [ "tN2kGroupFunctionHandlerForPGN126464", "classt_n2k_group_function_handler_for_p_g_n126464.html", "classt_n2k_group_function_handler_for_p_g_n126464" ],
    [ "tN2kGroupFunctionHandlerForPGN126993", "classt_n2k_group_function_handler_for_p_g_n126993.html", "classt_n2k_group_function_handler_for_p_g_n126993" ],
    [ "tN2kGroupFunctionHandlerForPGN126996", "classt_n2k_group_function_handler_for_p_g_n126996.html", "classt_n2k_group_function_handler_for_p_g_n126996" ],
    [ "tN2kGroupFunctionHandlerForPGN126998", "classt_n2k_group_function_handler_for_p_g_n126998.html", "classt_n2k_group_function_handler_for_p_g_n126998" ],
    [ "tN2kGroupFunctionHandlerForPGN60928", "classt_n2k_group_function_handler_for_p_g_n60928.html", "classt_n2k_group_function_handler_for_p_g_n60928" ],
    [ "tN2kMeteorlogicalStationData", "structt_n2k_meteorlogical_station_data.html", "structt_n2k_meteorlogical_station_data" ],
    [ "tN2kMsg", "classt_n2k_msg.html", "classt_n2k_msg" ],
    [ "tN2kScheduler", "classt_n2k_scheduler.html", "classt_n2k_scheduler" ],
    [ "tN2kSyncScheduler", "classt_n2k_sync_scheduler.html", "classt_n2k_sync_scheduler" ],
    [ "tNMEA2000", "classt_n_m_e_a2000.html", "classt_n_m_e_a2000" ],
    [ "tPriorityRingBuffer", "classt_priority_ring_buffer.html", "classt_priority_ring_buffer" ],
    [ "tRingBuffer", "classt_ring_buffer.html", "classt_ring_buffer" ],
    [ "tSatelliteInfo", "structt_satellite_info.html", "structt_satellite_info" ]
];