= NMEA2000 library for Arduino =

Object oriented NMEA2000 library for Arduino Boards

Library gives you a easy way to make NMEA2000->PC interface like Actisense NGT1
or e.g. temperature sensor node to NMEA2000 bus.

To use Arduino Due board internal CAN you will also need NMEA2000_due library and
due_can library, which you can download from  https://github.com/collin80/due_can

To use Arduino boards with MCP2515 CAN bus controller, you will also need NMEA2000_mcp library
and mcp_can library, which you can download from https://github.com/Seeed-Studio/CAN_BUS_Shield

== License ==

2015 Copyright (c) Kave Oy, www.kave.fi  All right reserved.

Author: Timo Lappalainen

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-
  1301  USA
