= NMEA2000 library for Arduino =

Object oriented NMEA2000 library for Arduino Boards

Library gives you a easy way to make NMEA2000->PC interface like Actisense NGT1
or e.g. temperature sensor node to NMEA2000 bus.

To use Arduino Due board internal CAN you will also need NMEA2000_due library and
due_can library, which you can download from  https://github.com/collin80/due_can

To use Arduino boards with MCP2515 CAN bus controller, you will also need NMEA2000_mcp library
and mcp_can library. mcp_can library can be originally found on https://github.com/Seeed-Studio/CAN_BUS_Shield
Currently NMEA2000_mcp library uses developed version of mcp_can library, which allows also to use 8MHz clock and
has been tested with Maple Mini. So until these improvements has not been implemented to Seeed-Studio,
use library found on https://github.com/peppeve/CAN_BUS_Shield

== Hardware setup ==

To use Arduino NMEA2000 library you will need either

- Arduino Due and CAN-bus_tranceiver chip e.g. MCP2562 or
SN65HVD234. I used MCP2562, since that was available also in DIP package.
Under Documents there is file ArduinoDUE_CAN_with_MCP2562.pdf for using MCP2562
and file ArduinoDue_CAN_with_SN65HVD234.jpg for using SN65HVD234.

- Arduino Mega and MCP2515 CAN-bus controller + MCP2551 CAN-bus_tranceiver or buy
CAN_BUS shield card. Under documents there is file ArduinoMega_CAN_with_MCP2515_MCP2551.pdf
for layout to build CAN-bus interface by yourself. MCP2515, MCP2551, ocillator and few
components cost only few euros, if you are handy and used to use soldering device.

Library has been also used with Maple Mini board, which is much cheaper than arduino.

If you using Arduino for transfering all messages to PC, I'll prefere Due version, since it is more powerful.
I Also prefere it, if you use handle messages (like GNSS) containing 8 byte double values. Arduino Mega has
only 4 byte double, so you may loose some accuracy.

== Software setup ==

Library has been developed with Arduino Software 1.6.5. I'll expect you are familiar with Arduino
and using libraries. When your Arduino environment is ready,</br>
- Download NMEA2000 library zip.</br>
- Download either NMEA2000_due or NMEA2000_mcp library zip depending you hw.</br>
- Download either due_can (https://github.com/collin80/due_can) or mcp_can (https://github.com/peppeve/CAN_BUS_Shield) 
library zip depending you hw.</br>
- Install all libraries (Add .ZIP library).</br>
- Open NMEA2000\Examples\TemperatureMonitor.</br>
- Connect you Arduino to USB and NMEA2000 bus.</br>
- Send sketch to Arduino.</br>
- If you have Multi Function Display (e.g. Garmin GMI-20) on your NMEA2000 bus, you should see on it's NMEA2000 bus devices new device
"Simple temp monitor" on the list.

So you are ready to play with your own device. Check also the NMEA2000\Examples\ActisenseListener, which reads all data
from NEMA2000 bus and sends it to PC.

== License ==

2015 Copyright (c) Kave Oy, www.kave.fi  All right reserved.

Author: Timo Lappalainen

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-
  1301  USA
