= NMEA2000 library for C++ =

Object oriented NMEA2000 library for Teensy, ESP, Arduino, MBED and Rasberry type Boards.
These board types has been tested, but library can be used also in other systems by writing
compatible CAN driver and wrapper for other hw specific functions.

Library gives you easy way to make different kind of NMEA2000 bus devices like
sensor transducers (battery, temperature, wind, engine, etc.), NMEA2000 information displays,
NMEA2000->PC interface (like Actisense NGT1), NMEA0183->NMEA2000 or NMEA2000->NMEA0183 converter.

Library fulfills NMEA 2000 mandatory functions and behaviour. Devices using library can pass NMEA2000
certification tests. Library has been used in several commercial certified products.

If you are familiar with library, here is quick link to the changes: 
https://ttlappalainen.github.io/NMEA2000/changes.html

Read more from the full documentation on Github Pages: 
https://ttlappalainen.github.io/NMEA2000/index.html


== License ==

MIT license

Copyright (c) 2015-2023 Timo Lappalainen, Kave Oy, www.kave.fi

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
