; PlatformIO Project Configuration File
;
; platform and lib_deps are pinned to specific versions due to recent compatibility
; issues with the latest espressif32 platform and NMEA2000 libraries.

[env:nodemcu-32s]
platform = espressif32 @ 6.12.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps = 
  ttlappalainen/NMEA2000-library @ ^4.17.2
  ttlappalainen/NMEA2000_esp32 @ ^1.0.3
